//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEvrakTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int raporId { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<int> evrakId { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> durumId { get; set; }
        public Nullable<int> yerId { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Evraklar Evraklar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Yerler Yerler { get; set; }
    }
}
